language: node_js
sudo: true
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: osx
node_js:
  - 10
  - 12
branches:
  except:
  - /^v[0-9]/
install:
  - yarn install
  - yarn global add codecov
  - yarn global add ts-node
script:
  - yarn bootstrap
  - yarn run test
  - yarn bundle

after_success:
  - codecov
cache:
  directories:
  - "$HOME/.yarn-cache"
