language: node_js
sudo: true
jobs:
  include:
    - os: linux
      dist: xenial
      node_js:
        - 10
    - os: linux
      dist: xenial
      node_js:
        - 12
    - os: linux
      dist: bionic
      node_js:
        - 10
    - os: linux
      dist: bionic
      node_js:
        - 12
    - os: osx
      node_js:
        - 10
    - os: osx
      node_js:
        - 12
    - os: windows
      node_js: "10.18"
      before_install:
        - npm install node-addon-api
        - npm install --global --production windows-build-tools --vs2015
        - npm config set msvs_version 2015 --global
    - os: windows
      node_js: 10
      before_install:
        - npm install --global --production windows-build-tools --vs2017
        - npm config set msvs_version 2017 --global
    - os: windows
      node_js: "12.18.3"
      before_install:
        - npm install node-addon-api
        - npm install --global --production windows-build-tools --vs2015
        - npm config set msvs_version 2015 --global
    - os: windows
      node_js: 12
      before_install:
        - npm install --global --production windows-build-tools --vs2017
        - npm config set msvs_version 2017 --global
branches:
  except:
  - /^v[0-9]/
install:
  - yarn install
  - yarn global add codecov
  - yarn global add ts-node
script:
  - yarn bootstrap
  - yarn run test
  - yarn bundle

after_success:
  - codecov
cache:
  directories:
  - "$HOME/.yarn-cache"
